# Generated by Django 4.2.2 on 2023-06-29 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_categroy'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='categroy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.categroy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default=1, upload_to='jobs/'),
            preserve_default=False,
        ),
    ]
